## variables


#### variable wraps a tensor and allows accumulation of gradients 

In [1]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.ones(2,2),requires_grad=True)

In [3]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
a.size()

torch.Size([2, 2])

In [5]:
b = Variable(torch.ones(2,2),requires_grad=True)

In [7]:
#behave similarly to tensors
print(a+b)


tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [8]:
torch.add(a,b)


tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)

In [9]:
torch.mul(a,b)


tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)

### Gradients

#### requires_grad allows calculation of gradients w.r.tthe variable

In [10]:
x = Variable(torch.ones(2),requires_grad=True)

In [13]:
y = 5 * (x+1) ** 2

In [14]:
y

tensor([20., 20.], grad_fn=<MulBackward>)

backward should only be called on a scalar or with gradient w.r.t the variable

In [15]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward>)

In [16]:
o.backward()

In [17]:
x.grad

tensor([10., 10.])

In [ ]:
#backward in detail
o.backward(torch.FloatTensor([1.0,1.0]))
x.grad