In [3]:
import torch


In [4]:
arr = [[1,2],[3,4]]

In [5]:
import numpy as np 

In [6]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [7]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [8]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [9]:
torch.rand(2,2)

tensor([[0.0923, 0.3722],
        [0.8052, 0.5196]])

seed for reusability 

In [11]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [12]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [13]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

# Numpy and Torch Bridge

In [14]:
np_arr = np.ones((2,2))

In [15]:
print(type(np_arr))

<class 'numpy.ndarray'>


In [17]:
t_tensor = torch.from_numpy(np_arr)

In [19]:
print(type(t_tensor))

<class 'torch.Tensor'>


In [20]:
np_arr_ne = np.ones((2,2),dtype=np.int8)
torch.from_numpy(np_arr_ne)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

torch to numpy

In [22]:
tensor_tensor = torch.ones(2,2)

In [24]:
t_n = tensor_tensor.numpy()

### tensors on cpu and gpu

In [25]:
tensor_cpu = torch.ones(2,2)

In [26]:
#cpu to gpu 
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [27]:
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

## tensor operations

resizing tensor

In [28]:
a = torch.ones(2,2)

In [29]:
a.size()

torch.Size([2, 2])

In [30]:
a.view(4)

tensor([1., 1., 1., 1.])

In [31]:
a.view(4).size()

torch.Size([4])

element wise addition

In [32]:
a = torch.ones(2,2)
b = torch.ones(2,2)

In [33]:
c = a + b

In [34]:
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [35]:
#inplace addition
c.add_(a)

tensor([[3., 3.],
        [3., 3.]])

In [37]:
#not in place
print(a.sub(b))
#inplace
print(c.sub_(b))

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [38]:
torch.mul(a,c)

tensor([[1., 1.],
        [1., 1.]])

In [39]:
torch.div(b,a)

tensor([[1., 1.],
        [1., 1.]])

tensor mean

In [40]:
a = torch.Tensor([1,2,3,4,4,5,6,7,8,9])

In [41]:
a.size()

torch.Size([10])

In [43]:
a.mean(dim=0)

tensor(4.9000)

Tensor Standard deviation

In [44]:
a = torch.Tensor([1,2,3,4,4,5,6,7,8,9])
a.std(dim=0)

tensor(2.6013)